services:
  - type: web
    name: chattyai-backend
    runtime: node
    region: oregon
    plan: standard # For production readiness
    buildCommand: |
      npm ci --production=false
      npm run smoke-test
    startCommand: |
      npm run migrate || echo "Migration failed, continuing..."
      npm start
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: DATABASE_URL
        fromDatabase:
          name: chattyai-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: chattyai-redis
          type: redis
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: VAPI_WEBHOOK_SECRET
        generateValue: true
      - key: DEFAULT_TENANT_ID
        value: "00000000-0000-0000-0000-000000000000"
    autoDeploy: true
    
databases:
  - name: chattyai-db
    plan: standard # Paid tier for connection pooling
    ipAllowList: [] # Allow connections from anywhere
    
  - name: chattyai-redis
    type: redis
    plan: standard # 256MB plan for 10x IOPS
    ipAllowList: []
    maxMemoryPolicy: allkeys-lru # Evict least recently used keys when full 