name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  NODE_VERSION: '20'

jobs:
  security-scan:
    name: Security & Quality Gate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Security audit
        run: npm audit --audit-level=high

      - name: Lint
        run: npm run lint || echo "Lint not configured"

      - name: Type check
        working-directory: ./thechattyai-frontend
        run: |
          npm ci
          npm run build

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    needs: security-scan
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Health check test
        run: |
          timeout 30 node google-calendar-api.js &
          SERVER_PID=$!
          sleep 5
          curl -f http://localhost:4000/healthz || exit 1
          kill $SERVER_PID

  deploy-backend:
    name: Deploy Backend to Render
    runs-on: ubuntu-latest
    needs: [security-scan, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Trigger Render Deploy
        run: |
          curl -X POST "https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}"

      - name: Wait for deployment
        run: sleep 60

      - name: Verify deployment
        run: |
          for i in {1..10}; do
            if curl -f https://chattyai-calendar-bot-1.onrender.com/healthz; then
              echo "Deployment successful"
              exit 0
            fi
            echo "Attempt $i failed, retrying..."
            sleep 30
          done
          echo "Deployment verification failed"
          exit 1

  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: [security-scan, test]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./thechattyai-frontend
          vercel-args: '--prod'

  notify:
    name: Deployment Notification
    runs-on: ubuntu-latest
    needs: [deploy-backend, deploy-frontend]
    if: always()
    steps:
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          text: |
            Deployment Status: ${{ needs.deploy-backend.result }} (Backend) / ${{ needs.deploy-frontend.result }} (Frontend)
            Health Check: https://chattyai-calendar-bot-1.onrender.com/healthz
            Frontend: https://app.thechattyai.com
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} 